services:
  postgres:
    image: postgres:17
    container_name: hr-cap-platform
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hr-cap-db
      POSTGRES_USER: hr_admin
      POSTGRES_PASSWORD: hr_admin

volumes:
  pgdata:
